/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.bitbuckets;

import org.bitbuckets.subsystems.helloworld.HelloWorldSubsystem;

public class App {

    public static void main(String[] args) {
        HelloWorldSubsystem helloWorldSubsystem = new HelloWorldSubsystem();

        // start off the state machine
        helloWorldSubsystem.periodic();

        // trigger a new state
        helloWorldSubsystem.triggerHelloWorld();
        helloWorldSubsystem.periodic();
        
        // we are idle now
        helloWorldSubsystem.periodic();
        helloWorldSubsystem.periodic();
        helloWorldSubsystem.periodic();
    }
}
