/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.bitbuckets;

import org.bitbuckets.subsystems.arm.ArmSubsystem;
import org.bitbuckets.subsystems.elevator.ElevatorSubsystem;

public class App {

    public static void main(String[] args) {
        ArmSubsystem armSubsystem = new ArmSubsystem();
        ElevatorSubsystem elevatorSubsystem = new ElevatorSubsystem(armSubsystem);

        // start off the state machine
        armSubsystem.periodic();
        elevatorSubsystem.periodic();
        
        // close the arm 
        armSubsystem.closeArm();

        // run the subsystems
        armSubsystem.periodic();
        elevatorSubsystem.periodic();

        // open the arm 
        armSubsystem.openArm();

        // run the subsystems
        armSubsystem.periodic();
        elevatorSubsystem.periodic();

    }

}
